# Generated by Django 4.0.5 on 2022-08-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_class', models.CharField(blank=True, max_length=16, null=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Класс авто',
                'verbose_name_plural': 'Классы авто',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Дата',
                'verbose_name_plural': 'Даты',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(blank=True, max_length=8, null=True, verbose_name='Оплата')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=24, null=True, verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Wash_man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man', models.CharField(blank=True, max_length=32, null=True, verbose_name='Мойщик')),
            ],
            options={
                'verbose_name': 'Мойщик',
                'verbose_name_plural': 'Мойщики',
            },
        ),
        migrations.CreateModel(
            name='Wash_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип мойки',
                'verbose_name_plural': 'Типы мойки',
            },
        ),
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('grz', models.CharField(blank=True, max_length=9, null=True, verbose_name='ГРЗ автомобиля')),
                ('car_mark', models.CharField(blank=True, max_length=32, null=True, verbose_name='Марка автомобиля')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('notes', models.TextField(blank=True, max_length=360, null=True, verbose_name='Примечания')),
                ('sale', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('car_class', models.ForeignKey(blank=True, db_column='car_class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.car_class', verbose_name='Класс авто')),
                ('date', models.ForeignKey(blank=True, db_column='date', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.date', verbose_name='Дата')),
                ('pay_type', models.ForeignKey(blank=True, db_column='pay', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pay', verbose_name='Способ оплаты')),
                ('service', models.ManyToManyField(to='core.service', verbose_name='Услуги')),
                ('wash_man', models.ForeignKey(blank=True, db_column='wash_man', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.wash_man', verbose_name='Мойщик')),
                ('wash_type', models.ForeignKey(blank=True, db_column='wash_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.wash_type', verbose_name='Тип мойки')),
            ],
            options={
                'verbose_name': 'Бланк',
                'verbose_name_plural': 'Бланки',
            },
        ),
    ]
