# Generated by Django 4.0.5 on 2022-08-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blank_super_clean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ('-id',), 'verbose_name': 'Дата', 'verbose_name_plural': 'Даты'},
        ),
        migrations.AddField(
            model_name='blank',
            name='done_clean',
            field=models.BooleanField(default=False, verbose_name='Готова'),
        ),
        migrations.AddField(
            model_name='blank',
            name='night_clean',
            field=models.BooleanField(default=False, verbose_name='Ночная'),
        ),
    ]
