# Generated by Django 4.0.5 on 2022-09-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_date_options_blank_done_clean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='price_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='price_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='price_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blank',
            name='car_class',
            field=models.ForeignKey(db_column='car_class', default=0, on_delete=django.db.models.deletion.CASCADE, to='core.car_class', verbose_name='Класс авто'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='car_mark',
            field=models.CharField(default='', max_length=32, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='date',
            field=models.ForeignKey(db_column='date', default=0, on_delete=django.db.models.deletion.CASCADE, to='core.date', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='grz',
            field=models.CharField(default='', max_length=9, verbose_name='ГРЗ автомобиля'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='notes',
            field=models.TextField(default='', max_length=360, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='pay_type',
            field=models.ForeignKey(db_column='pay', default=0, on_delete=django.db.models.deletion.CASCADE, to='core.pay', verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='sale',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='wash_man',
            field=models.ForeignKey(db_column='wash_man', default=0, on_delete=django.db.models.deletion.CASCADE, to='core.wash_man', verbose_name='Мойщик'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='wash_type',
            field=models.ForeignKey(db_column='wash_type', default=0, on_delete=django.db.models.deletion.CASCADE, to='core.wash_type', verbose_name='Тип мойки'),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
    ]
