# Generated by Django 4.0.5 on 2022-09-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_price_1_service_price_2_service_price_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price_1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_4',
        ),
    ]
